### ISSUE TITLE
License for use?

### ISSUE THREAD

**Issue by carnesen** [BeloborodovDS/MobilenetSSDFace#4]
Hello! Would you be willing to specify a license for use of the software contained in this repository? GitHub makes it pretty easy to do https://help.github.com/en/articles/adding-a-license-to-a-repository . Thanks!

**Comment by BeloborodovDS** [comment]
Hello @carnesen!
I never expected anyone to need the license, to be honest. 
Anyway, I added the license to the project.

**Comment by carnesen** [comment]
Many thanks!
