### ISSUE TITLE
About the aspect ratio in .prototxt

### ISSUE THREAD

**Issue by XiangpengZeng** [BeloborodovDS/MobilenetSSDFace#5]
Hello, could I ask what's the value of aspect ratio in each priorbox layer? I have not found them

**Comment by BeloborodovDS** [comment]
The first one is always 1.0, even if it's not specified.
You can add more boxes with different ratios like this ([source](https://github.com/chuanqi305/MobileNet-SSD)):
```
layer {
  name: "conv17_2_mbox_priorbox"
  type: "PriorBox"
  bottom: "conv17_2"
  bottom: "data"
  top: "conv17_2_mbox_priorbox"
  prior_box_param {
    min_size: 285.0
    max_size: 300.0
    aspect_ratio: 2.0
    aspect_ratio: 3.0
    flip: true
    clip: false
    variance: 0.1
    variance: 0.1
    variance: 0.2
    variance: 0.2
    offset: 0.5
  }
}
```
Also see [source code](https://github.com/intel/caffe/blob/master/src/caffe/layers/prior_box_layer.cpp) for this layer to see how prior boxes are generated.
